version: '3.1'

services:
   
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_database
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 
      - 8025:8025

  wordpress:
    build:
      context: ./docker
      dockerfile: dockerfile-wordpress
    restart: always
    depends_on: 
      - db
      - mailhog
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_database
    volumes:
      - ./public_html:/var/www/html

  

    